language: node_js
sudo: required
node_js:
  - "6"

env:
  - CXX=g++-4.8

os:
  - linux
  - osx

before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential -y

script: python build.py