version: '{build}'

image: Visual Studio 2017

platform:
  - x64

install:
  - ps: Install-Product node 6 x64
  - node --version
  - npm --version

build_script:
  - npm install
  - python build.py
  - dir C:\\MinGW\\msys\\1.0\\bin\\scp.exe

test: off
